ALTER TABLE "Product" ALTER COLUMN "price" DROP DEFAULT;
ALTER TABLE "Product" ALTER COLUMN "price" TYPE integer USING round("price"::numeric, 0)::integer;
ALTER TABLE "Product" ALTER COLUMN "price" SET DEFAULT 0;
ALTER TABLE "Product" ALTER COLUMN "compareAtPrice" TYPE integer USING round("compareAtPrice"::numeric, 0)::integer;
ALTER TABLE "ProductVariant" ALTER COLUMN "price" TYPE integer USING round("price"::numeric, 0)::integer;
ALTER TABLE "ProductVariant" ALTER COLUMN "compareAtPrice" TYPE integer USING round("compareAtPrice"::numeric, 0)::integer;
ALTER TABLE "Cart" ALTER COLUMN "itemsPrice" TYPE integer USING round("itemsPrice"::numeric, 0)::integer;
ALTER TABLE "Cart" ALTER COLUMN "shippingPrice" TYPE integer USING round("shippingPrice"::numeric, 0)::integer;
ALTER TABLE "Cart" ALTER COLUMN "taxPrice" TYPE integer USING round("taxPrice"::numeric, 0)::integer;
ALTER TABLE "Cart" ALTER COLUMN "totalPrice" TYPE integer USING round("totalPrice"::numeric, 0)::integer;
ALTER TABLE "Cart" ALTER COLUMN "couponDiscount" DROP DEFAULT;
ALTER TABLE "Cart" ALTER COLUMN "couponDiscount" TYPE integer USING round("couponDiscount"::numeric, 0)::integer;
ALTER TABLE "Cart" ALTER COLUMN "couponDiscount" SET DEFAULT 0;
ALTER TABLE "Order" ALTER COLUMN "itemsPrice" TYPE integer USING round("itemsPrice"::numeric, 0)::integer;
ALTER TABLE "Order" ALTER COLUMN "shippingPrice" TYPE integer USING round("shippingPrice"::numeric, 0)::integer;
ALTER TABLE "Order" ALTER COLUMN "taxPrice" TYPE integer USING round("taxPrice"::numeric, 0)::integer;
ALTER TABLE "Order" ALTER COLUMN "totalPrice" TYPE integer USING round("totalPrice"::numeric, 0)::integer;
ALTER TABLE "Order" ALTER COLUMN "couponDiscount" DROP DEFAULT;
ALTER TABLE "Order" ALTER COLUMN "couponDiscount" TYPE integer USING round("couponDiscount"::numeric, 0)::integer;
ALTER TABLE "Order" ALTER COLUMN "couponDiscount" SET DEFAULT 0;
ALTER TABLE "OrderItem" ALTER COLUMN "price" TYPE integer USING round("price"::numeric, 0)::integer;
ALTER TABLE "Coupon" ALTER COLUMN "value" TYPE integer USING round("value"::numeric, 0)::integer;
ALTER TABLE "Coupon" ALTER COLUMN "minCartTotal" DROP DEFAULT;
ALTER TABLE "Coupon" ALTER COLUMN "minCartTotal" TYPE integer USING round("minCartTotal"::numeric, 0)::integer;
ALTER TABLE "Coupon" ALTER COLUMN "minCartTotal" SET DEFAULT 0;
